#pragma once

namespace TCP
{

/******************************************************************************
错误码定义
******************************************************************************/
typedef enum ErrorCode
{
	BIND_LOCAL_PORT_INVALID = 1,

	LISTEN_ASSOCIATE_SOCKET_PARAM,
	LISTEN_ASSOCIATE_SOCKET_FAIL,
	LISTEN_LISTEN_FAIL,
	LISTEN_ALLOC_PARAM,

	RECV_ALLOC_PARAM,

	CONN_ASSOCIATE_SOCKET_PARAM,
	CONN_ASSOCIATE_SOCKET_FAIL,
	CONN_REMOTE_ADDR_INVALID,
	CONN_ALLOC_PARAM,

	SEND_ALLOC_PARAM,
	SEND_LIMIT_RECV_PARAM,

	BRIDGE_SOCKET_INVALID,

	CLOSE_SOCKET_INVALID,
	CLOSE_ERASE_EXCEPTION,

	STARTUP_CREATE_IOCP_STARTUP_FAIL,
	STARTUP_CREATE_IOCP_VER_ERR,
	STARTUP_CREATE_IOCP_CREATE_FAIL,

	STARTUP_IOCP_THREAD_THREAD_CNT_INVALID,
	STARTUP_IOCP_THREAD_NEW_SEM_EXCEPTION,
	STARTUP_IOCP_THREAD_NEW_SEM_NULL,
	STARTUP_IOCP_THREAD_SEM_LOCK_FAIL,
	STARTUP_IOCP_THREAD_BEGIN_FAIL,

	LOAD_EX_FUNC_SOCKET_INVALID,
	LOAD_EX_FUNC_GET_ACCEPT_FAIL,
	LOAD_EX_FUNC_GET_CONNECT_FAIL,
	LOAD_EX_FUNC_GET_GET_ADDR_FAIL,
	LOAD_EX_FUNC_CLOSE_SOCKET_FAIL,

	SET_SOCKET_VALID_INSERT_PARAM,
	SET_SOCKET_VALID_INSERT_FAIL,

	POST_ACCEPT_CONTEXT_NULL,
	POST_ACCEPT_ASSOCIATE_SOCKET_PARAM,
	POST_ACCEPT_ASSOCIATE_SOCKET_FAIL,
	POST_ACCEPT_ACCEPT_PARAM,
	POST_ACCEPT_ACCEPT_FAIL,

	POST_RECV_RECV_PARAM,
	POST_RECV_RECV_FAIL,

	POST_CONN_CONN_PARAM,
	POST_CONN_CONN_FAIL,

	POST_SEND_SEND_PARAM,
	POST_SEND_SEND_FAIL,

	EXIT_IOCP_THREAD_IOCP_NULL,
	EXIT_IOCP_THREAD_POST_EXIT_MSG_FAIL,
	EXIT_IOCP_THREAD_THREAD_SEM_NULL,
	EXIT_IOCP_THREAD_LOCK_FAIL,

	CLEANUP_NET_CLEANUP_FAIL,
	CLEANUP_NET_IOCP_NULL,
	CLEANUP_NET_CLOSE_IOCP_FAIL,

	EXIT_IOCP_WORK_THREAD_SEM_NULL,
	EXIT_IOCP_WORK_SEM_UNLOCK_FAIL,

	GET_IO_NOTICE_IOCP_NULL,

	PROCESS_ACCEPT_CANCEL_CALLBACK_PARAM,

	PROCESS_DISCON_CALLBACK_PARAM,

	PROCESS_IO_NOTICE_CONTEXT_NULL,
	PROCESS_IO_NOTICE_UNKNOWN_OPERATE,

	PROCESS_ACCEPT_NOTICE_ACCEPT_FAIL,
	PROCESS_ACCEPT_NOTICE_GET_ADDR_PARAM,
	PROCESS_ACCEPT_NOTICE_CALLBACK_PARAM,

	PROCESS_CONN_NOTICE_CALLBACK_PARAM,

	PROCESS_SEND_NOTICE_SEND_FAIL,
	PROCESS_SEND_NOTICE_CONTEXT_NULL,
	PROCESS_SEND_NOTICE_SEND_LEN_INVALID,

	PROCESS_RECV_NOTICE_RECV_FAIL,
	PROCESS_RECV_NOTICE_CALLBACK_PARAM,

	RESUME_RECV_RESUME_PARAM,

	POST_RECV_CONTINUE_PAUSE_PARAM,

	IS_SOCKET_VALID_SOCKET_INVALID,
	IS_SOCKET_VALID_CONTEXT_NULL,

	POST_ACCEPT_CANCEL_POST_PARAM,
	POST_ACCEPT_CANCEL_POST_FAIL,

	POST_DISCON_POST_PARAM,
	POST_DISCON_POST_FAIL,
}EErrorCode;

/******************************************************************************
输出提示回调函数定义
参数：
	strTip			提示
	strClass		类名
	iErr			错误码
	strErr			错误串
	pThis			回调this指针
******************************************************************************/
typedef void (* PFNPutTip)(string strTip, string strClass, int iErr
	, string strErr, void * pThis);

}